### ISSUE TITLE
Think this might be hardcoded to http rather than https

### ISSUE THREAD

**Issue by axfelix** [artefactual/fixity#15]
Probably fixable (I'll open a PR myself later this week), but we have this running on a server that was recently redeployed with https and it's now throwing

    Unable to connect to storage service instance at http://localhost:8000/ (is it running?)

**Comment by sromkey** [comment]
Thanks Alex- I'm going to re-file this in [archivematica/issues](https://github.com/archivematica/Issues) which is where we're tracking all issues in the Archivematica environment now. Thanks!
